services:
  mongodb:
    restart: always
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  talents-api:
    restart: always
    build:
      context: ./src
      args:
        VERSION: ${VERSION:-0.0.0}
        COMMIT_HASH: ${COMMIT_HASH:-n/a}
        BUILD_TIMESTAMP: ${BUILD_TIMESTAMP:-n/a}
        BUILD_TYPE: prod
    ports:
      - "8011:8080"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - PORT=8080
    depends_on:
      - mongodb

volumes:
  mongo-data:
