version: "3"

vars:
  BINARY_DIR: ./bin
  APP_NAME: talents-api
  CODE_DIR: ./src
  PACKAGE: "talents-api"

tasks:
  default:

  dev:
    desc: build project binary for development
    cmds:
      - task: lint
      - task: docker-build
        vars:
          BUILD: "dev"
    silent: true

  docker-up:
    desc: build and run project with docker
    vars:
      VERSION:
        sh: git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null || git rev-parse --short HEAD
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BUILD_TIMESTAMP:
        sh: date '+%Y-%m-%dT%H:%M:%S'
    cmds:
      - cmd: VERSION={{.VERSION}} COMMIT_HASH={{.COMMIT_HASH}} BUILD_TIMESTAMP={{.BUILD_TIMESTAMP}} docker compose up --build
    silent: false

  docker-build:
    desc: build project with docker
    vars:
      VERSION:
        sh: git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null | sed 's/^.//'
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BUILD_TIMESTAMP:
        sh: date '+%Y-%m-%dT%H:%M:%S'
    cmds:
      - cmd: "echo 'Build info\n\tVersion:\t{{.VERSION}}\n\tCommit:\t\t{{.COMMIT_HASH}}\n\tTime Stamp:\t{{.BUILD_TIMESTAMP}}'"
      - cmd: VERSION={{.VERSION}} COMMIT_HASH={{.COMMIT_HASH}} BUILD_TIMESTAMP={{.BUILD_TIMESTAMP}} docker compose build {{.APP_NAME}}
    silent: true
    internal: true

  build-int:
    desc: build project binary
    vars:
      VERSION:
        sh: git describe --tags --always --abbrev=0 --match='v[0-9]*.[0-9]*.[0-9]*' 2> /dev/null | sed 's/^.//'
      COMMIT_HASH:
        sh: git rev-parse --short HEAD
      BUILD_TIMESTAMP:
        sh: date '+%Y-%m-%dT%H:%M:%S'
      LDFLAGS: "-X {{.PACKAGE}}/app.Build={{.BUILD}} -X {{.PACKAGE}}/app.Version={{.VERSION}} -X {{.PACKAGE}}/app.CommitHash={{.COMMIT_HASH}} -X {{.PACKAGE}}/app.BuildTimestamp={{.BUILD_TIMESTAMP}}"
    cmds:
      - cmd: "echo 'Build info\n\tBuild:\t\t{{.BUILD}}\n\tVersion:\t{{.VERSION}}\n\tCommit:\t\t{{.COMMIT_HASH}}\n\tTime Stamp:\t{{.BUILD_TIMESTAMP}}'"
      - cmd: mkdir -p {{.BINARY_DIR}}
      - cmd: go build -C {{.CODE_DIR}} -ldflags="{{.LDFLAGS}}" -v -o ../{{.BINARY_DIR}}/{{.APP_NAME}}
    silent: true
    internal: true

  build:
    desc: build a project
    vars:
      BUILD: "prod"
    cmds:
      - task: docker-build
        vars:
          BUILD: "{{.BUILD}}"
    silent: true

  lint:
    desc: Run linters and formatters
    dir: "{{.CODE_DIR}}"
    cmds:
      - cmd: go vet
      - cmd: go mod tidy
      - cmd: go fmt
      - cmd: swag fmt
      - cmd: swag init --parseDependency
    silent: false
